### ISSUE TITLE
When to perform code generation

### ISSUE THREAD

**Issue by raderio** [etiennestuder/gradle-jooq-plugin#100]
When to perform code generation?
Before every run(build/deploy) or test command? Or the task should be called separated from other tasks?
What is common practice for this action?

**Comment by lukaseder** [comment]
For the record, I have provided an answer to this question here: https://github.com/jOOQ/jOOQ/issues/8804#issuecomment-502559230

**Comment by etiennestuder** [comment]
If you configure your Gradle jOOQ task with proper inputs, Gradle will only build the sources when needed, i.e. when the to-be-generated sources are not present, the jOOQ configuration has changed, or the db schema has changed. Once you have this in place, you can make the source code generation part of the compilation life-cycle stage and always invoke it. Due to the incremental build feature of Gradle (or the build cache functionality), Gradle will only execute the code generation when there is a need to do so.
