### ISSUE TITLE
Code was not generated after the database was changed

### ISSUE THREAD

**Issue by ansidev** [etiennestuder/gradle-jooq-plugin#142]
Gradle Generator Config:
```
    generator {
      database {
        name = dbMetaName
        inputSchema = dbName
      }
      generate {
        deprecated = false
        records = true
        pojos = true
        daos = false
      }
      target {
        packageName = 'foo.bar'
        directory = 'src/main/java'
      }
    }
```

#### Problem:
- The database was changed, but when I run Gradle task `generateDatabaseJooqSchemaSource`, no code was generated.
- I must delete the package folder and run the task `generateDatabaseJooqSchemaSource` again to see the code changes.

So I am asking if I miss some configuration.

Thanks!

**Comment by etiennestuder** [comment]
The jOOQ plugin does not detect (and does not intend to detect) schema changes. It is up to your build to configure the generateJooq task such that changes to the db lead to changes to the task inputs which will then lead to a rerun of the task. For example, when using Flyway, the db schema files used to create the schema can also be set as inputs on the jooqGenerate task.

**Comment by lukaseder** [comment]
> The jOOQ plugin does not detect (and does not intend to detect) schema changes. It is up to your build to configure the generateJooq task such that changes to the db lead to changes to the task inputs which will then lead to a rerun of the task

I'm trying to understand this, because I had similar support requests in the past. I take that this is an optimisation where the potentially costly querying and generation of code is prevented unless there's a clear sign that this is needed.

`jOOQ-codegen` prevents re-generation of files that haven't been changed (such as to allow for incremental compilation). But out of the box, `jOOQ-codegen` still has to reverse engineer the entire schema to figure this out. For large schemas, that does take time and it's good to avoid this, when we can be sure it isn't needed.

Your optimisation works well when database change management is set up correctly, in case of which the above work can be avoided. But if a quick-and-dirty project setup (e.g. for a jOOQ evaluation, or for something entirely else) doesn't invest in database change management (yet), perhaps this optimisation is premature?

I wonder how many people run into this and think "this isn't working at all"

**Comment by ansidev** [comment]
@etiennestuder To me, this is a bug because the generated code does not reflect the database structure, even after running the generate task. That make code cannot be built and/or run properly.

**Comment by etiennestuder** [comment]
@ansidev Feel free to consider it a bug if you wish. I will not implement anything in the jOOQ plugin regardless since it is very project specific how db changes are triggered and tracked, and how to optimize the detection of such changes.

You can avoid the problem by adding `jooqGenerate.upToDateWhen { false }`.

**Comment by etiennestuder** [comment]
> Your optimisation works well when database change management is set up correctly, in case of which the above work can be avoided. But if a quick-and-dirty project setup (e.g. for a jOOQ evaluation, or for something entirely else) doesn't invest in database change management (yet), perhaps this optimisation is premature?
> 
> I wonder how many people run into this and think "this isn't working at all"

I see your (valid) point, @lukaseder. I think I'm going to add a section to the docs to explain how to avoid the task not being rerun when the db changes and the jOOQ plugin not knowing about it. Basically, the solution I provided in the comment above.

**Comment by lukaseder** [comment]
> I see your (valid) point, @lukaseder. I think I'm going to add a section to the docs to explain how to avoid the task not being rerun when the db changes and the jOOQ plugin not knowing about it. Basically, the solution I provided in the comment above.

I wonder if the defaults are correct, if things don't seem to work out of the box, and have to be understood first... At the very least I'd say this creates unnecessary frustrations with new users who might try something entirely else based on this experience.

When a user first sets up code generation, it should Just Work™. So, without any automatic "up-to-date-schema-source", the default of `upToDateWhen { false }` seems reasonable, because otherwise, the output and behaviour is wrong and requires debugging or reading of some detail in the manual when a user (rightfully, IMO) shouldn't really have to at this point of an evaluation process. They have more important things to do than tune an optimisation that doesn't work for them. So, I concur with @ansidev, I feel this is a bug.

Later, when database change management is set up, the optimisation starts being useful, *but only then*. If the third party database change management tool cannot be detected automatically with confidence (it probably could be in the case of Flyway or Liquibase), then there could still be a check that validates if, after a jOOQ code generation run, anything has changed at all and needs recompiling, because `jOOQ-codegen` already prevents overwriting files that haven't been modified. So, if nothing requires re-compiling, then an `INFO` or `WARN` message could be logged hinting at this optimisation being available, so users can set it up manually, or set `upToDateWhen { false }` explicitly to at least mute the warning.

`jOOQ-codegen` has a similar feature that is useful when someone uses Flyway, the catalog and schema version providers:
https://www.jooq.org/doc/latest/manual/code-generation/codegen-advanced/codegen-config-database/codegen-database-version-providers/

If that feature is turned on, then some mechanism can be defined that provides `jOOQ-codegen` with the current schema version. `jOOQ-codegen` will then produce a `@Generated` annotation with that version in it, and at the beginning of the code generation run, simply check if that annotation is present, and if the version is the same. I don't think it would be a good idea to do all of this by default for optimisation's sake, and just e.g. generate `1.0.0` in the absence of an explicit, user-defined schema version provider.

(Not strictly related: this discussion made me think if we should auto-detect the Flyway/Liquibase schema version tables and read the versions from there, by default, as well: https://github.com/jOOQ/jOOQ/issues/10630)

**Comment by etiennestuder** [comment]
> When a user first sets up code generation, it should Just Work™. So, without any automatic "up-to-date-schema-source", the default of `upToDateWhen { false }` seems reasonable, because otherwise, the output and behaviour is wrong and requires debugging or reading of some detail in the manual when a user (rightfully, IMO) shouldn't really have to at this point of an evaluation process. They have more important things to do than tune an optimisation that doesn't work for them. So, I concur with @ansidev, I feel this is a bug.

Can reading of a few paragraphs of documentation before using a tool no longer be expected of users? My plugin does not target those users that first complain that something is not working before reading the one-page documentation (docs and examples that I invested a lot of time into in order to make it easy to maximise the benefit of using the plugin).

Build performance should not be considered an afterthought or second-class citizen. It's absolutely critical. Having a build that runs code generation unnecessarily is a serious impediment to developer productivity.

> (Not strictly related: this discussion made me think if we should auto-detect the Flyway/Liquibase schema version tables and read the versions from there, by default, as well: jOOQ/jOOQ#10630)

In our own build, we make the Flyway scripts an input to the jooqGenerate task. This is very reliable and a very fast way to determine at build time whether to either rerun the code generation or to take the sources from the build cache. Poking into the db is slower and adds unnecessary complexity. I will add a build example for that in the near future.

**Comment by etiennestuder** [comment]
See [5.1.0](https://github.com/etiennestuder/gradle-jooq-plugin/releases/tag/v5.1.0).

**Comment by lukaseder** [comment]
> Can reading of a few paragraphs of documentation before using a tool no longer be expected of users?

You're assuming a lot here. For example, that a user has already decided that jOOQ *must* be used and Gradle *must* be used. But that assumption is wrong. People jump ship because of far lesser UX hurdles and use something else, if they're in a hurry.

I know quite a few people who didn't get this plugin to work right away, and even reverted back to the official jOOQ Maven plugin for their POCs. But they were frustrated already by that time. I really appreciate the time you've invested in your work and your tutorials, and I'm sure, others do, as well. But we all know, and it happens to the best, that sometimes, we just don't read "the thing", for whatever reason.

The number of paragraphs that is assumed someone has read is not really relevant. It might just have been overlooked. They might have read some obsolete tutorial elsewhere. Or they just don't want to read, but expect products to "just work". That might be a naive expectation, but what do you prefer, the apt-get install experience of PostgreSQL, or the several hours of tweaking Oracle configuration flags until you've wrecked your Windows registry, spending the next day re-installing Windows *and* Oracle Enterprise Edition? I am a firm believer of a "it just works" first impression of any software.

I would normally not care as much about third party work, but this one is the one that is officially recommended by the jOOQ manual (after you talked me into that 😉), so here I am - I have a stake in the user experience of this plugin.

> Build performance should not be considered an afterthought or second-class citizen. It's absolutely critical. Having a build that runs code generation unnecessarily is a serious impediment to developer productivity.

Yes it is critical. But not for everyone. Not for someone first trying out jOOQ. So, how can we help those people *and* the ones you made this for?

For example, if this is something very important to you, how about if the build just fails if nothing explicit has been configured, with an error message showing the options? Silently not generating anything leads to a long debugging session that can be avoided.

> In our own build, we make the Flyway scripts an input to the jooqGenerate task. This is very reliable and a very fast way to determine at build time whether to either rerun the code generation or to take the sources from the build cache. Poking into the db is slower and adds unnecessary complexity. I will add a build example for that in the near future.

I prefer your solution as well, but that's something you can do outside of the core jOOQ libraries.

This doesn't exclude adding additional options to the jOOQ library. I can totally imagine setups where there are several completely separate build processes that can't communicate with each other directly, so the best place to look for version information would indeed be the database. Yes, you're saving a few milliseconds, maybe even a second of setting up a database connection.

But preventing code generation entirely prevents possibly minutes. If that happens automatically, what's to lose, especially if someone isn't using Gradle and/or your plugin?

**Comment by etiennestuder** [comment]
> I know quite a few people who didn't get this plugin to work right away, and even reverted back to the official jOOQ Maven plugin for their POCs. But they were frustrated already by that time. I really appreciate the time you've invested in your work and your tutorials, and I'm sure, others do, as well. But we all know, and it happens to the best, that sometimes, we just don't read "the thing", for whatever reason.

Thanks for that perspective. I never thought people try out jOOQ for the first time by running it with a Gradle build right away. That's a bit mixing apples and pears :-)

> The number of paragraphs that is assumed someone has read is not really relevant. It might just have been overlooked. They might have read some obsolete tutorial elsewhere. Or they just don't want to read, but expect products to "just work". 

"Just works" is a very lose definition. It sounds to me like "as long as it generates something and does not fail at generation time, it works". That's a very low standard for an evaluation. But understand your point that there should be as little friction by the build tool as possible while people evaluate jOOQ.

> I prefer your solution as well, but that's something you can do outside of the core jOOQ libraries.

Absolutely. It's a pure build feature.

> But preventing code generation entirely prevents possibly minutes. If that happens automatically, what's to lose, especially if someone isn't using Gradle and/or your plugin?

Yes, absolutely. And that's exactly what you get by using Gradle tasks, defining all inputs, and then Gradle not running the code generation tasks when nothing has changed or when the generated sources can be taken from the build cache.

All good, IMO, @lukaseder. As of version 5.1.0, the jOOQ task is run everytime, unless someone explicitly opts-in to participating in incremental builds (which requires them to ensure db schema changes are reflected in the inputs of the jOOQ task). I hope this will lead to less frustration by people evaluating jOOQ. It's such a great product and people should embrace it and be excited about it, like we at Gradle are.

**Comment by lukaseder** [comment]
> Thanks for that perspective. I never thought people try out jOOQ for the first time by running it with a Gradle build right away. That's a bit mixing apples and pears :-)

Why? They've used Gradle for ages, now they want to use jOOQ. They check the manual and find this plugin. They *love* Gradle, they want to use it for their jOOQ evaluation as well.

> "Just works" is a very lose definition. It sounds to me like "as long as it generates something and does not fail at generation time, it works". That's a very low standard for an evaluation. But understand your point that there should be as little friction by the build tool as possible while people evaluate jOOQ.

Here's a formal one, which I really like: https://www.nngroup.com/articles/usability-101-introduction-to-usability/

**Comment by lukaseder** [comment]
For the record, I'm still intrigued by your very useful optimisation, and I'd like to help people better discover it. jOOQ can detect whether a code generation run was necessary or not (independently of whether it was run by Gradle, Maven, standalone, etc.). So, if it wasn't necessary, we'll print the options users have to prevent this: https://github.com/jOOQ/jOOQ/issues/10648

While looking into this, I've found 2 additional cases that can get in the way of people evaluating jOOQ, where having this optimisation here turned on by default might not make too much sense:

- When code is generated manually only (and checked in version control). A lot of people do this, and they especially do this when evaluating and playing around with jOOQ
- When people modify other input parameters to the code generation (other than the schema), such as e.g. forced type configurations, converter implementations, generator strategies, jOOQ upgrades, JDBC driver upgrades, database upgrades, etc. I guess some of these things can be detected automatically by Gradle?

**Comment by etiennestuder** [comment]
> While looking into this, I've found 2 additional cases that can get in the way of people evaluating jOOQ, where having this optimisation here turned on by default might not make too much sense:

It's no longer turned on by default. See version [5.1.0](https://github.com/etiennestuder/gradle-jooq-plugin/releases/tag/v5.1.0).

> When people modify other input parameters to the code generation (other than the schema), such as e.g. forced type configurations, converter implementations, generator strategies, jOOQ upgrades, JDBC driver upgrades, database upgrades, etc. I guess some of these things can be detected automatically by Gradle?

The plugin already considers all these things as task inputs. Even when the user opts-in to the incremental build feature, if any of these parameters you mentioned change, the task is re-executed.

**Comment by lukaseder** [comment]
> It's no longer turned on by default. See version [5.1.0](https://github.com/etiennestuder/gradle-jooq-plugin/releases/tag/v5.1.0).

I get it. I added to the previous arguments, for completeness' sake.

> The plugin already considers all these things as task inputs. Even when the user opts-in to the incremental build feature, if any of these parameters you mentioned change, the task is re-executed.

Excellent!

**Comment by etiennestuder** [comment]
@lukaseder We've added an [example](https://github.com/etiennestuder/gradle-jooq-plugin/tree/master/example/configure_jooq_with_flyway) on how to use Flyway together with jOOQ in a Gradle build, and how this can be leveraged to have a jOOQ task that participates in incremental builds and in build caching, meaning the jOOQ task will only execute if and only if something has changed that potentially impacts the jOOQ sources being generated.

I've also tried to add answer your question on change detection from above in more detail via code comment:
https://github.com/etiennestuder/gradle-jooq-plugin/blob/master/example/configure_jooq_with_flyway/build.gradle#L54-L57

**Comment by lukaseder** [comment]
Thanks a lot for the hint, @etiennestuder. I'll check how the example can be linked from the manual, I think this is very useful.
