### ISSUE TITLE
Upgrading from v4.x to v5.x makes multiple configurations delete each other

### ISSUE THREAD

**Issue by taven** [etiennestuder/gradle-jooq-plugin#154]
The plugin was setup to have multiple configurations with the idea that all these configurations can be run to generate all the required code.
When upgrading to v5.2 and following the migration steps the tasks now can't be run all together as each subsequent task replaces the previous tasks generated code.

**Comment by etiennestuder** [comment]
With Gradle, you should not have different tasks writing their results to the same output directory (so called overlapping outputs). Since every configuration you define in the DSL of the gradle-jooq-plugin creates a separate task (and each one clears the output before writing its result), these jOOQ configurations should not point to the same output diectory.

Check the examples secction and go through previous issues to find more info:
https://github.com/etiennestuder/gradle-jooq-plugin/blob/master/example/configure_different_jooq_sources_for_same_target_source_set/build.gradle
