### ISSUE TITLE
Workaround for jOOQ Version for Plugin causing NPE

### ISSUE THREAD

**Issue by bosohn** [etiennestuder/gradle-jooq-plugin#163]
Plugin's jOOQ version is 3.13.5 while latest jOOQ version is 3.14.6. I can use latest jOOQ version by overriding jooq.version.

However, in my project, files generated by the plugin for 3.14.6 is used during gradle build for flyway Java migration. Flyway Java migration code is built with generated files for 3.14.6. When these Java migration code runs as part of gradle flyway migration task, it results in the following error:
      org.jooq.impl.SQLDataType.LOCALDATETIME(I)Lorg/jooq/DataType

LOCALDATETIME(I)Lorg/jooq/DataType is newly defined in 3.14.6. Since gradle loaded jOOQ version 3.13.5 for jOOQ plugin, it cannot resolve methods defined in 3.14.6 when running flyway Java migration.

To workaround this, I tried forcing jOOQ plugin to use 3.14.6 instead of 3.13.5 using the following for buildscript.
    dependencies {
        classpath "org.jooq:jooq:3.14.6"
    }

Flyway migration works fine with this with jOOQ 2.14.6 generated code but this results in NPE during generateJooq task blocking jOOQ code generation. I need to manually switch back and forth build.gradle to make it work for flyway migration (force jOOQ 3.14.6) and for jOOQ code generation (remove plugin jOOQ version override).

Any solution to get around this issue would be much appreciated.
Thank you

**Comment by etiennestuder** [comment]
How do you invoke Flyway? Do you use the Flyway Gradle plugin? It is hard to understand for me what your build setup looks like. Below, you can find some background information that hopefully gives you the understanding how you can fix your issue. If not, please provide a self-contained, working build example that we can look at.

There are different classpaths involved here:

1. **The classpath used to map the jOOQ Gradle DSL to the jOOQ XML configuration file that is fed into the jOOQ code generator.** By default, the jOOQ version "bundled" with the jOOQ Gradle plugin is used. You can enforce a different version as explained [here](https://github.com/etiennestuder/gradle-jooq-plugin#gradle-groovy-dsl-3).

```
buildscript {
    configurations['classpath'].resolutionStrategy.eachDependency {
        if (requested.group == 'org.jooq') {
            useVersion '3.12.4'
        }
    }
}
```

Note that the jOOQ version defined in the jOOQ Gradle DSL has no impact since at the time of parsing the build that version is not yet read. That version will only be used for the actual project configurations, but not for the buildscript's classpath configuration.

2. **The classpath used to invoke the jOOQ code generator (in a separate JVM).** By default, it uses the version defined in the jOOQ DSL in your build as explained [here](https://github.com/etiennestuder/gradle-jooq-plugin#gradle-groovy-dsl-2).

```
jooq {
  version = '3.14.7'
}
```

In case you want to have your jOOQ code generator use a different version of a certain jOOQ library than what you set on the jOOQ Gradle DSL, you can do the following:

```
configurations["jooqGenerator"].resolutionStrategy.eachDependency {
    if (requested.group == "org.jooq") && requested.name == "joor") { useVersion("0.9.13") }
}
```

3. **The classpath used when compiling your source set containing the generated jOOQ source files.** By default, the jOOQ libraries are used in the version defined in the jOOQ Gradle DSL in your build as explained [here](https://github.com/etiennestuder/gradle-jooq-plugin#gradle-groovy-dsl-2).

4. **The classpath used when invoking Flyway.** By default, the jOOQ libraries are used in the version defined in the jOOQ Gradle DSL in your build as explained [here](https://github.com/etiennestuder/gradle-jooq-plugin#gradle-groovy-dsl-2). You can find an example for the Flyway plugin and jOOQ gradle plugin [here](https://github.com/etiennestuder/gradle-jooq-plugin/blob/master/example/configure_jooq_with_flyway/build.gradle).

While I laid out the different classpaths possibly involved, I by no means want to suggest that you manipulate them as individually as listed above. Typically, it is enough to set the jOOQ version on the [jOOQ Gradle DSL](https://github.com/etiennestuder/gradle-jooq-plugin#gradle-groovy-dsl-2) and sometimes also on the [buildscript classpath](https://github.com/etiennestuder/gradle-jooq-plugin#gradle-groovy-dsl-3). In your case, possibly also on the classpath of the Flyway execution.

**Comment by bosohn** [comment]
Thanks and I really appreciate your detail response.

Adjusting jOOQ version in buildscript as described in **The classpath used when invoking Flyway** section in your response solved my problem and all works fine.

Thanks again for your help.
Brian
