### ISSUE TITLE
allInputsDeclared doesn't seem to work properly

### ISSUE THREAD

**Issue by gotson** [etiennestuder/gradle-jooq-plugin#173]
Hi,

I have the plugin configured to get the schema from a SQLite database, which is generated by a Flyway script. The Flyway task has [its inputs declared](https://github.com/gotson/komga/blob/740ad476d17ccee6505da4c5f7dad27fee395385/komga/build.gradle.kts#L220) via the Gradle API, and will rerun only when migrations are added.

However, the JooqGenerate task, with the `allInputsDeclared=true` doesn't rerun after the Flyway task ran, and is incorrectly marked as up to date.

In addition, by specifying that the JooqGenerate task [depends on another task](https://github.com/gotson/komga/blob/740ad476d17ccee6505da4c5f7dad27fee395385/komga/build.gradle.kts#L253), this should override the `allInputsDeclared`.

Result:

```
17:30:55: Executing task 'generateJooq'...

> Task :komga:kaptGenerateStubsFlywayKotlin
> Task :komga:kaptFlywayKotlin UP-TO-DATE
> Task :komga:compileFlywayKotlin UP-TO-DATE
> Task :komga:compileFlywayJava NO-SOURCE
> Task :komga:processFlywayResources
> Task :komga:flywayClasses
> Task :komga:flywayMigrate
> Task :komga:generateJooq UP-TO-DATE
```

Did i miss something in the [configuration of the plugin](https://github.com/gotson/komga/blob/740ad476d17ccee6505da4c5f7dad27fee395385/komga/build.gradle.kts#L229-L254) ?

**Comment by etiennestuder** [comment]
Did you take a look at this example?
https://github.com/etiennestuder/gradle-jooq-plugin/tree/master/example/configure_jooq_with_flyway

**Comment by etiennestuder** [comment]
`allInputsDeclared=true` works properly, but you should not set it to true unless you have actually specified all inputs, and that - for example - includes the schema files from which the database is created that jooq will run against.

**Comment by gotson** [comment]
> Did you take a look at this example?

This looks like what I have.

> and that - for example - includes the schema files from which the database is created that jooq will run against.

What do you mean by schema files exactly ? SQLite doesn't have schema.

--

The documentation doesn't really cover what are the different possible inputs, nor what is covered exactly by `allInputsDeclared`.

**Comment by gotson** [comment]
I have added gradle inputs definition, like so:

```kts
tasks.named<nu.studer.gradle.jooq.JooqGenerate>("generateJooq") {
  migrationDirsSqlite.forEach { inputs.dir(it) }
  allInputsDeclared.set(true)
  dependsOn("flywayMigrate")
}
```

This is working.

Is that what you were referring to when saying "but you should not set it to true unless you have actually specified all inputs" ?

**Comment by etiennestuder** [comment]
> This looks like what I have.

No, since you did not specify the state of the database as an input to the jooq task. This is different from the example I linked to where the flyway sql migration files are declared as additional inputs on the jooq task.

> What do you mean by schema files exactly ? SQLite doesn't have schema.

These are your schema files from which you create the database in sqlite, aren't they?
https://github.com/gotson/komga/tree/740ad476d17ccee6505da4c5f7dad27fee395385/komga/src/flyway/resources/db/migration/sqlite

> Is that what you were referring to when saying but you should not set it to true unless you have actually specified all inputs ?

Whatever influences the output of jooq's source code generation needs to be declared as an input of the jooq task. Some inputs are already declared by the gradle-jooq-plugin out-of-the-box, like the jooq-codegen configuration itself. But, that is not enough to decide whether to rerun the jooq task or not. Since jooq usually runs against a database and derives the source code from the existing tables, etc., you need to somehow represent the state of the database as an input to the jooq task. One common approach is to use the schema files that were used to generate the database (in a previous step of the build) as the input to the jooq task. This way, whenever you change the schema files, the jooq task will rerun.

> I have added gradle inputs definition, like so:

This looks OK now.
