### ISSUE TITLE
Bug with subprojects and PRO JOOQ edition

### ISSUE THREAD

**Issue by Dartaan** [etiennestuder/gradle-jooq-plugin#183]
I found a bug / configuration defect when using gradle subprojects.

When 1 subproject contains a JOOQ, and another subproject uses the first subproject to access the database, the second subproject has to include both editions (oss JOOQ and  pro JOOQ). As a result I have to replace oss edition to pro edition by script.
Sampe project - [https://github.com/Dartaan/jooq-codegen-plugin-issue](https://github.com/Dartaan/jooq-codegen-plugin-issue) (it requires a repositiory with pro jooq)
Left all information in [module/build.gradle.kts](https://github.com/Dartaan/jooq-codegen-plugin-issue/blob/master/module/build.gradle.kts)

The presumptive location of the error is [JooqPlugin.java#L55](https://github.com/etiennestuder/gradle-jooq-plugin/blob/06154c587b864be7830fff15eb3aeba051342237/src/main/groovy/nu/studer/gradle/jooq/JooqPlugin.java#L55)

**Comment by klesniewski** [comment]
I ran into the same issue. The project, that has jOOQ plugin applied has a dependency on `org.jooq:jooq` which is turned into desired edition and version with metadata. This metadata isn't however populated to consuming project, so they are left with `org.jooq:jooq` dependency, which fails to resolve. Based on your code @Dartaan I added such workaround to our project:

```groovy
dependencies {
    // Workaround for https://github.com/etiennestuder/gradle-jooq-plugin/issues/183
    implementation "org.jooq.pro-java-11:jooq:3.15.1"
    modules {
        module("org.jooq:jooq") {
            replacedBy("org.jooq.pro-java-11:jooq", "nu.studer.jooq bugfix #183")
        }
    }
}
```

The `modules` section instruct Gradle to use `org.jooq.pro-java-11:jooq` instead of `org.jooq:jooq` if there is a conflict. To create the conflict, we add an explicit dependency on `org.jooq.pro-java-11:jooq` - otherwise the modules section has no effect.

The workaround has to be added to every project consuming the jOOQ project, which is far from ideal.

**Comment by apatrida** [comment]
@klesniewski maybe do this at the top level of your gradle and wrap that in

```
configurations.all { ... }
```

to apply to all projects.  My version is like this:

```
configurations.all {
    val jooqGroupId: String by project

    dependencies {
        modules {
            module("org.jooq:jooq") {
                if (jooqGroupId != "org.group") {
                    replacedBy("${jooqGroupId}:jooq", "nu.studer.jooq bugfix #183")
                }
            }
        }
    }
}
```

and I can see it working:
```
\--- org.jooq:jooq -> org.jooq.pro:jooq:3.18.0-SNAPSHOT (*)
+--- org.jooq.pro:jooq-kotlin:3.18.0-SNAPSHOT
|    +--- org.jooq.pro:jooq:3.18.0-SNAPSHOT
|    +--- org.jooq.pro:jooq-kotlin:3.18.0-SNAPSHOT (*)
|    |    +--- org.jooq.pro:jooq-kotlin:3.18.0-SNAPSHOT (*)
\--- org.jooq:jooq -> org.jooq.pro:jooq:3.18.0-SNAPSHOT (*)
```

**Comment by apatrida** [comment]
even with workarounds, get errors like:

```
Execution failed for task ':search:search-sync:dependencies'.
> Could not resolve all dependencies for configuration ':search:search-sync:quarkusDependency'.
   > Could not find org.jooq:jooq:.
     Required by:
        ...
```

so now I'm guessing the quarkus plugin is grabbing this in a place that isn't being updated by resolution changing.

**Comment by apatrida** [comment]
Ok, I had to move my code to top level build script to apply to everything and now it solves the issues.

**Comment by etiennestuder** [comment]
The gradle-jooq-plugin 9.0 no longer registers any custom dependency resolution rules.
