### ISSUE TITLE
New APIs on org.jooq.util.jaxb.Configuration require new jooq-gradle-plugin release

### ISSUE THREAD

**Issue by etiennestuder** [etiennestuder/gradle-jooq-plugin#23]
The config of the code generation via DSL is mapped to a org.jooq.util.jaxb.Configuration instance, which is from the jOOQ version with which the gradle-jooq-plugin was built. This dependency should be cut by either mapping everything to a non-jOOQ object at config time, or by allowing the user to configure a jOOQ xml config file backed by the well-known jOOQ schema (or potentially both).

**Comment by lukaseder** [comment]
The simplest solution here is probably not to hard-wire any dependency on a specific version of the `org.jooq.util.jaxb.Configuration` type. If you supply an XML string to `org.jooq.util.GenerationTool.generate(String xml)`, for instance, jOOQ will parse that string using JAXB and [the most up-to-date XSD](http://www.jooq.org/xsd). These XSD files can be expected to be backwards compatible.

So, I'm guessing that an XML-based API call will be best, here. Of course, if you find any other way to operate, I'm very happy to discuss new jOOQ API in `GenerationTool` to accommodate this plugin's needs.

**Comment by etiennestuder** [comment]
We already create the jOOQ config xml and feed it into the code generator. But, the thing is that we currently do this by mapping the Gradle DSL to the `org.jooq.util.jaxb.Configuration` type and from there to XML.

I'd like to let things settle a bit, collect and fix any issues that come up, and then make the switch to a new DSL such that the user simply specifies the jOOQ config xml to apply. This will also give the user xml schema support at development name, and remove any dependencies on jOOQ from the Gradle runtime.

**Comment by lukaseder** [comment]
OK, that makes sense. Well, if you support the latest minor release, given that the XSD's are backwards compatible, your suggested approach will probably work.

**Comment by ben-manes** [comment]
The [original plugin](https://github.com/ben-manes/gradle-jooq-plugin/tree/master/src/main/groovy/com/github/benmanes/gradle/jooq) used `MarkupBuilder` by proxying from the extension's `methodMissing` to build the XML. This way it relied on the XSD validation and the plugin contained almost no code. Since this plugin was built to supersede that one, provides better semantics, and followed the same pattern of using the `methodMissing` technique, I'd guess there was a good reason why @etiennestuder originally preferred operating on the Java type instead.

**Comment by lukaseder** [comment]
@ben-manes I think the discussion in this issue is outdated. The current implementation works on the JAXB-annotated objects and discovers them automatically. But the issue that arose with https://github.com/etiennestuder/gradle-jooq-plugin/issues/71 is probably caused by the fact that the "bootstrapping" type `org.jooq.util.jaxb.Configuration` (needed to navigate the type hierarchy) was moved to `org.jooq.meta.jaxb.Configuration`.

**Comment by ben-manes** [comment]
Right. I just wanted to make sure #71 didn't prompt a naive rewrite to something like `MarkupBuilder` without considering the consequences. The problem with that DSL approach was that it wrote the XML immediately, so updates after the DSL block were appended instead of overwritten. The typed object approach resolves that quirk, since the intermediate object hierarchy can be traversed and updated. So there are tradeoffs that lean towards the more complex approach taken by @etiennestuder.

**Comment by lukaseder** [comment]
> didn't prompt a naive rewrite to something like MarkupBuilder without considering the consequences.

Don't worry :)

**Comment by etiennestuder** [comment]
I will stick to the current approach, even at the expense of being more work on my end to keep uptodate with the latest jOOQ code generation configuration options.
