### ISSUE TITLE
Stackoverflow when using database.forcedTypes

### ISSUE THREAD

**Issue by advoretsky** [etiennestuder/gradle-jooq-plugin#27]
When I add
```
forcedTypes = [
                    {
                        userType = 'java.time.LocalDateTime'
                        converter = 'com.company.dao.LocalDateTimeConverter'
                        expression = '.*\\.DATE_TIME.*'
                    }
               ]
```
under 
```
jooq {
   main(sourceSets.main) {
      generator {
           database {

```
I get 
```
java.lang.StackOverflowError
	at nu.studer.gradle.util.Objects.hasCustomHashCode(Objects.java:179)
	at nu.studer.gradle.util.Objects.deepHashCode(Objects.java:125)
	at nu.studer.gradle.util.Objects$DeepHashCodeComparator.compare(Objects.java:215)
	at nu.studer.gradle.util.Objects.sort(Objects.java:192)
	at nu.studer.gradle.util.Objects.deepHashCode(Objects.java:104)
	at nu.studer.gradle.util.Objects$DeepHashCodeComparator.compare(Objects.java:215)
	at nu.studer.gradle.util.Objects.sort(Objects.java:192)
```
on both 1.0.5 and 2.0.2 versions

**Comment by demongaorui** [comment]
Running into the same issue when generating codes for MySQL with jooq version'3.8.5' and following configuration.
```json
                forcedTypes = [
                    {
                        name = 'BOOLEAN'
                        types = '(?i:TINYINT(\\s*\\(\\d+\\))?(\\s*UNSIGNED)?)'
                    }
                ]
```

**Comment by uberbrodt** [comment]
Same, with jooq version 3.8.1 & plugin 2.0.2

```
                forcedTypes = [
                    {
                        userType = "java.lang.String"
                        binding = "com.traitify.jooq.customtypes.PostgresLTreeJooqBinding"
                        expression = ".*ORG_PATH"
                    }
```

**Comment by felipefzdz** [comment]
Hi @advoretsky, @demongaorui and @uberbrodt.

The proper way of including Jooq complex types with sequences has been documented here: https://github.com/etiennestuder/gradle-jooq-plugin#typical-pitfalls. An automated test that exercises that scenario has been added: https://github.com/etiennestuder/gradle-jooq-plugin/blob/master/src/test/groovy/nu/studer/gradle/jooq/JooqFuncTest.groovy#L103

/cc @lukaseder

**Comment by lukaseder** [comment]
Hmm, interesting. Is there anything that could be done from the jOOQ side (backwards-compatibly) that would enable that Groovy list style? The jOOQ code generator configuration just works this way because this is standard practice when defining lists in XSD.

Would be really great if idiomatic configuration style could be used. After all, "idiomacy" is the main feature of this plugin, no?

**Comment by etiennestuder** [comment]
Hi @lukaseder. What we plan to do first of all is to provide better error reporting for scenarios like the one of this issue, so people can easily understand the problem and how to fix it.

I'm not sure I want to add two ways to specifying lists (and sets, etc.) in the DSL. Also, the DSL has no explicit goal to be idiomatic-Groovy. In contrary, the fact that the Gradle DSL is parsed by Groovy is more of an implementation detail.

The main feature of this plugin (or at least what drove me to write this plugin) is that you can declare the jOOQ source code generator configuration in your build build rather than in an external xml file.

**Comment by lukaseder** [comment]
> the fact that the Gradle DSL is parsed by Groovy is more of an implementation detail.

Interesting, I missed that bit. Thanks for the explanation!
