### ISSUE TITLE
Add an INFO log message stating the plugin version

### ISSUE THREAD

**Issue by lukaseder** [etiennestuder/gradle-jooq-plugin#31]
Sometimes, when giving support to users of this plugin, I don't immediately notice that they're using this plugin, e.g. because there's no stack trace, log message, etc.

It would be useful if prior to calling `GenerationTool`, an INFO level log message would be created with:

- Package name
- Plugin name
- Plugin version

Ideally, you'd be using the `org.jooq.tools.JooqLogger` for this, so this would log to the same place as the remaining logs.

**Comment by etiennestuder** [comment]
I will look into it, @lukaseder.

**Comment by etiennestuder** [comment]
@lukaseder Any chance you could provide a cmd line option to pass this information to the GenerationTool, e.g. `--origin`, which would allow a call of `java org.jooq.util.GenerationTool --origin "gradle-jooq-plugin:2.0.3"`?

Otherwise it gets quite convoluted since I currently call the GenerationTool in a separate process (on purpose!), and without the proposed change above, I would have to wrap the call to the GenerationTool in my own class that is launched in the external process, making that class available in a library and pulling it in as a separate external dependency. Thus, instead of an additional dependency that is created and pulled in just to add a logging statement, it would be great if the GenerationTool could log the origin passed in via cmd line. It would also allow other callers to make use of that feature of passing in who they are.

Or, as an alternative, you could read a system property (if present) and log it. For example, `jooq.generationTool.origin`, i.e. `java org.jooq.util.GenerationTool -Djooq.generationTool.origin=gradle-jooq-plugin:2.0.3`

**Comment by lukaseder** [comment]
Oh, I see. I forgot about that separate process.

I'm not a big fan of command line options / system properties for these things. They need to be documented / maintained, which means they'll break and cause more harm than they add value.
