### ISSUE TITLE
Special characters in password issue (oracle)

### ISSUE THREAD

**Issue by lukasito** [etiennestuder/gradle-jooq-plugin#39]
We're having problem connect to **oracle** database using `gradle-jooq-plugin`.
It still results in `java.sql.SQLException: ORA-01017: invalid username/password; logon denied` Even if our password is correct.

We assume that problem might be with wrong encoding of special characters present in password like
 `ß ) $ %`

[jOOQ official style of generating resources](https://github.com/jOOQ/jOOQ/tree/master/jOOQ-examples/jOOQ-codegen-gradle) is working well and without problems.

**Comment by etiennestuder** [comment]
@lukasito In order to try and get to the bottom of this:

1 Can you paste the config you declare in the Gradle build file? (of course not using the real password but something similar in terms of characters being used)

2 Can you check on the Oracle side what username/password it receives and how it differs from what you specify in the Gradle build?

**Comment by etiennestuder** [comment]
I'm closing this for now. Feel free to open again if you can provide more info.
