### ISSUE TITLE
Reusing pre-generated code or generating code without a database

### ISSUE THREAD

**Issue by gregorko** [etiennestuder/gradle-jooq-plugin#67]
Hello..

the gradle plugin assumes that every developer or CI server has a database available that can be used to generate the code. This is usually note the case.
I'm looking for a way to trigger code generation manually and then adding it to version control. Currently this is a bit difficult since the plugin is regularly deleting the code added to version control and makes the build fail.
After reading multiple issues about this workflow. It appears to me that the manual triggered code generation is not a supported use case currently.
Like suggested in #59 I'm currently generating the code to src/main/jooq and add the files to version control. During builds on other machines the code gets deleted during clean. Compilation will fail. Generating it again would also fail because there is no database available.

Any solution to this?

**Comment by etiennestuder** [comment]
Hi @gregorko. 

Thanks for the clear explanation of the issue. There is a solution to what you want to achieve.

The first two items in the _Samples_ section demonstrate how you can avoid the deletion of the generated sources when calling `clean`, and how you can uncouple the compilation of the project from the source code generation:
https://github.com/etiennestuder/gradle-jooq-plugin#samples

Since this comes up repeatedly, I've also added an explanation under the _Pitfalls_ section:
https://github.com/etiennestuder/gradle-jooq-plugin#generating-sources-into-shared-folders-eg-srcmainjava

I hope this helps.

**Comment by lukaseder** [comment]
> the gradle plugin assumes that every developer or CI server has a database available that can be used to generate the code. This is usually note the case.

Unrelated to Gradle, do note that there are also 3 ways of generating code without needing a database connection:

- From an XML file: https://www.jooq.org/doc/latest/manual/code-generation/codegen-xml
- From a DDL file: https://www.jooq.org/doc/latest/manual/code-generation/codegen-ddl
- From JPA-annotated entities: https://www.jooq.org/doc/latest/manual/code-generation/codegen-jpa

These approaches currently do not support all the code generation features (e.g. vendor-specific stuff, procedures, etc.) but they might still be sufficient for general use-cases.

**Comment by etiennestuder** [comment]
@gregorko As of v2.0.10, running the `clean` task does no longer remove any generated jOOQ sources located outside the `build` directory.
