### ISSUE TITLE
Java version question

### ISSUE THREAD

**Issue by dsvensson** [etiennestuder/gradle-jooq-plugin#691]
Switched to this plugin from the upstream plugin to get gradle toolchain support, only to notice that the plugin release classes target bytecode 61 / java 17. Nothing weird as this is stated in the readme. Just curious why this is, given that the plugin supports gradle toolchain. Why not relax the constraints on what jvm is used to launch gradle? Is there any reason you don't target java 8 byte code for all releases, at least for the parts of the code that runs within the jvm that launched gradle?

**Comment by etiennestuder** [comment]
The OSS version of the jOOQ libraries, on which this plugin depends, require Java 17.

**Comment by dsvensson** [comment]
Ah, ofc. 🤦 I wish there was native launcher that jumped straight over to gradle toolchain to get around the problem of one jvm launching gradle, and another jvm executing some part of some of the tasks declared. Obviously off topic, just struggles. 😂

**Comment by etiennestuder** [comment]
The reason for the undesired coupling is that the gradle-jooq-plugin requires the jOOQ library on the path in order to generate the jOOQ config XML file from the DSL provided in the Gradle build. If the DSL the gradle-jooq-plugin provided was not dynamically mapped to the config understood by jOOQ, there would be no dependency on the jOOQ library and thus no dependency on a specific version of Java when running the Gradle build.
