### ISSUE TITLE
Not able to convert enum array in postgres

### ISSUE THREAD

**Issue by traptimittal** [etiennestuder/gradle-jooq-plugin#82]
I am trying to convert a column which is enum array to enum array object but the plugin is not able to use the converter.

**postgres:**
```
CREATE TYPE color AS ENUM ('RED', 'BLUE', 'GREEN');
CREATE TABLE colors
(
    colors color[],
);
```

**Converter (Kotlin):**
```
open class ColorConverter : EnumConverter<jooq.enums.Color, Color>(jooq.enums.Color::class.java, Color::class.java) {
}
```

**build file:**
```
forcedTypes {
    forcedType {
        userType = 'Color'
        enumConverter = 'true'
        types = 'color'
    }
}
```

When I put types='.color', it tries to convert the colors column. But that fails because colors is an array.
I want that it should convert color sql type.

Am I doing something wrong?

**Comment by lukaseder** [comment]
You have to provide a converter for the enum array in this case, not for the individual enum. Definitely a limitation of the code generator. The reason why you could use `.color` is because the `.` matches any character (the expression being a regular expression), and PostgreSQL reports array types of `x` as `_x` in the `pg_catalog`.

I hope this helps

**Comment by traptimittal** [comment]
Yes, I thought the same. Anyway I have resolved it by creating my own mapper. Would be great if the change could be incorporated in a future release. Thanks!
